
// Objective-C API for talking to the following Go packages
//
//	github.com/d991d/hometunnel/core/mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __HometunnelCore_FRAMEWORK_H__
#define __HometunnelCore_FRAMEWORK_H__

#include "Mobile.objc.h"
#include "Universe.objc.h"

#endif
