// Objective-C API for talking to github.com/d991d/hometunnel/core/mobile Go package.
//   gobind -lang=objc github.com/d991d/hometunnel/core/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Mobile_H__
#define __Mobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class MobileEngine;
@class MobileInviteParams;
@class MobileKeyPairHex;
@protocol MobileEventListener;
@class MobileEventListener;

@protocol MobileEventListener <NSObject>
/**
 * OnEvent is called for status, stats, error, and log events.
payload is a JSON-encoded map — see eventPayload for the shape.
 */
- (void)onEvent:(NSString* _Nullable)payload;
@end

/**
 * Engine manages a single VPN client connection.
Create one instance, call SetListener, then Connect.
 */
@interface MobileEngine : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewEngine creates a new Engine instance.
 */
- (nullable instancetype)init;
/**
 * Connect initiates a VPN connection. Non-blocking — events arrive via listener.
serverAddr: "1.2.3.4:7788"
token:      opaque invite token string
displayName: shown to the server operator (can be empty)
 */
- (void)connect:(NSString* _Nullable)serverAddr token:(NSString* _Nullable)token displayName:(NSString* _Nullable)displayName;
/**
 * Disconnect tears down the active connection.
 */
- (void)disconnect;
/**
 * IsConnected returns true when a VPN session is active.
 */
- (BOOL)isConnected;
/**
 * MTU returns the negotiated tunnel MTU, or 0 if not connected.
 */
- (long)mtu;
/**
 * ReadPacket blocks until a decrypted IP packet arrives from the server.
The Android VpnService calls this in a goroutine and writes the result to
its TUN file descriptor. Returns nil when the engine shuts down.
 */
- (NSData* _Nullable)readPacket;
/**
 * SetListener registers the callback that receives JSON event strings.
Must be called before Connect.
 */
- (void)setListener:(id<MobileEventListener> _Nullable)l;
/**
 * VirtualIP returns the assigned VPN address (e.g. "10.8.0.2"), or "".
 */
- (NSString* _Nonnull)virtualIP;
/**
 * WritePacket encrypts an outbound IP packet (read from TUN by VpnService) and
sends it over the UDP tunnel. Returns "" on success or an error string.
 */
- (NSString* _Nonnull)writePacket:(NSData* _Nullable)ipPkt;
@end

/**
 * InviteParams holds the result of ParseInviteLink.
 */
@interface MobileInviteParams : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull serverAddr;
@property (nonatomic) NSString* _Nonnull token;
@property (nonatomic) NSString* _Nonnull error;
@end

/**
 * KeyPairHex holds a hex-encoded X25519 key pair (utility, not required for VPN).
 */
@interface MobileKeyPairHex : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull public;
@property (nonatomic) NSString* _Nonnull private;
@property (nonatomic) NSString* _Nonnull error;
@end

/**
 * Author returns the project author handle.
 */
FOUNDATION_EXPORT NSString* _Nonnull MobileAuthor(void);

/**
 * GenerateKeyPairHex returns a new X25519 key pair as hex strings.
 */
FOUNDATION_EXPORT MobileKeyPairHex* _Nullable MobileGenerateKeyPairHex(void);

/**
 * NewEngine creates a new Engine instance.
 */
FOUNDATION_EXPORT MobileEngine* _Nullable MobileNewEngine(void);

/**
 * ParseInviteLink extracts serverAddr and token from a HomeTunnel invite URL.
Accepts "hometunnel://connect?server=...&token=..." and https:// equivalents.
 */
FOUNDATION_EXPORT MobileInviteParams* _Nullable MobileParseInviteLink(NSString* _Nullable link);

/**
 * Version returns the HomeTunnel version string.
 */
FOUNDATION_EXPORT NSString* _Nonnull MobileVersion(void);

@class MobileEventListener;

/**
 * EventListener receives async events from the VPN engine.
Implement this interface in Kotlin/Java and pass to Engine.SetListener.
 */
@interface MobileEventListener : NSObject <goSeqRefInterface, MobileEventListener> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * OnEvent is called for status, stats, error, and log events.
payload is a JSON-encoded map — see eventPayload for the shape.
 */
- (void)onEvent:(NSString* _Nullable)payload;
@end

#endif
